/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lc_lp_LCPlayer */

#ifndef _Included_com_lc_lp_LCPlayer
#define _Included_com_lc_lp_LCPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lc_lp_LCPlayer_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkInitGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkInitGL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkResizeGL
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkResizeGL
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkPaintGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkPaintGL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
