/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lc_lp_LCPlayer */

#ifndef _Included_com_lc_lp_LCPlayer
#define _Included_com_lc_lp_LCPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lc_lp_LCPlayer_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkInitGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkInitGL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkResizeGL
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkResizeGL
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkPaintGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkPaintGL
  (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkInitVideoPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkInitVideoPlayer
        (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkStartPlayerWithFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkStartPlayerWithFile
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkPauseVideoPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkPauseVideoPlay
        (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkStopVideoPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkStopVideoPlayer
        (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkGetVideoSizeRatio
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_lc_lp_LCPlayer_ndkGetVideoSizeRatio
        (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkGetVideoTotalSeconds
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_lc_lp_LCPlayer_ndkGetVideoTotalSeconds
        (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkSeekMedia
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkSeekMedia
        (JNIEnv *, jobject, jfloat);


/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkGetPlayStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lc_lp_LCPlayer_ndkGetPlayStatus
        (JNIEnv *, jobject);

/*
 * Class:     com_lc_lp_LCPlayer
 * Method:    ndkPlayVideoPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_lp_LCPlayer_ndkPlayVideoPlay
        (JNIEnv *, jobject) ;


#ifdef __cplusplus
}
#endif
#endif
